### TYPE YOUR NAME HERE: Conor Murray

## ISM 5644 - Programming for Analytics

## Exam - Coding Section

### Task:
The code cells in this notebook have been left blank. Your task is to complete these cells and provide the execution results. Once you have completed the test, you should publish your notebook code (the code in the .ipynb file) as a "Secret Gist" on your GitHub repository and obtain the Gist ID.

### Submission Format:
There are two deliverables of this exam: 1) the Gist ID and 2) the completed .ipynb file. Both of these should be submitted on Canvas using the corresponding submission link.

### Important: Do not forget to <u>run</u> the cells before submitting the document.

#### Q1. Use the cell below to enter your code for this question.
Question 1:

Note: This question has 2 steps.
Step 1:
Write a function that takes two inputs:

1) a string consisting of a single letter (e.g., 'e')

2) a long string consisting of some letters (e.g., 'HELLo WORld')

and counts how many times the single letter (1st input) occurs in the long string (2nd input). The function should ignore capitalization – i.e., uppercase 'E' should be counted as 'e', etc. The output of the function should be the frequency count of the letter.
Step 2:
|
Write a loop that iteratively calls the function you developed in the first step to count how many times each letter in a given list (e.g., ['a', 'e', 'o']) occurs in the long string consisting of some letters (2nd input of Step 1).

Below is a sample output after completing both steps.

longString = 'HELLo WORld'

aList = ['a', 'e', 'o']

Output (after defining the function and running the loop): 

The letter a occurs 0 times in the long string.

The letter e occurs 1 times in the long string.

The letter o occurs 2 times in the long string.

In [138]:
short = ['a', 'e', 'o']
long = 'HEllO worlD'
def listCheck(short, long):
    long = long.lower().strip()
    for i in short:
        count = 0
        for f in long:
            if i == f:
                count += 1
        print('The Letter', i, 'occurs',  count, 'times in the long string')
print(listCheck(short,long))

The Letter a occurs 0 times in the long string
The Letter e occurs 1 times in the long string
The Letter o occurs 2 times in the long string
None

#### Q2. Use the cell below to enter your code for this question. 
Assume that there exists a file named “aFile.txt” in the local disk. Write a program that prompts the user for a positive integer n as an input. The program should write the first n characters of each line in “aFile.txt” to a new file, named “newFile.txt”. The program should write the entire line, if n is greater than that line’s length. Below is a sample input and output for n = 10.

Input - aFile.txt:

First line of the file

Second line of the file

Third

Output - newFile.txt:

First line

Second lin

Third

In [140]:
aFile = open('aFile.txt', 'r')
newFile = open('newFile.txt', 'w')
n = int(input('Enter a positive integer'))

for line in aFile:
    line = obj.readline
    if len(line) < n:
        x = n - len(line)
        newFile.write(x)
        print('less than')
    else:
        newFile.write(line)
        print('more than')
aFile.close()
newFile.close()

Enter a positive integer 10

#### Q3. Use the cell below to enter your code for this question.
Question 3:

Assume that there exists a file named “numbersWords.txt” in the local disk. Each line of this file consists of some integer numbers (int) and words (str). Write a program that finds the largest number in this file, and prints out this number as well as the number of the line this number was in. Below is a sample input and output:

Input - numbersWords.txt:

random 346 numbers and

233 words are in 306

This file you 15663 need to find

4 the largest number here 592

Output:

The largest number: 15663

Found in line: 3

In [160]:
i = open('numbersWords.txt', 'r')
largest = 0
lineCount = 1 
for line in i:
    words = line.strip().split(' ')
    for f in words:
        try:
            num = int(f)
            if num > largest:
                largest = num
                lineCount += 1
        except:
            continue
print('Largest:', largest)
print('Found in line:', lineCount)

Largest: 15663
Found in line: 3

Question 4:

Download the following file to your local machine: NHL_data.csvDownload NHL_data.csv

The data set contains statistics for some of the National Hockey League teams across the years.

Question: Perform the tasks listed below using the Pandas Library. Notice that these tasks are divided into 3 cells. Please only use the designated cell area in the Jupyter file to write down your corresponding code. After importing the file at the beginning, you can continue working on the same data (i.e., you don't need to re-import the data for each individual cell).

#### Q4 Cell 1. Use the cell below to enter your code for the 1st cell of Q4.
Cell #1:

Import the downloaded data into the Python environment as a Pandas DataFrame.
Drop the column titled "GamesPlayed" from the DataFrame.
Select the first 10 observations and the first 5 columns from the data and display the values. Do NOT assign the selection to anything -- simply display the values on the screen.

In [43]:
import pandas as pd
df = pd.read_table('NHL_data.csv', delimiter=',')
df = df.drop((['GamesPlayed']), axis=1,)
df.iloc[0:10, 0:5]

   Year          Team  Wins  Losses  Shots
0  2012   LOS ANGELES    16       4   30.6
1  2012    NEW JERSEY    14      10   28.4
2  2012    NY RANGERS    10      10   29.3
3  2012       PHOENIX     9       7   26.7
4  2012    WASHINGTON     7       7   27.6
5  2012     NASHVILLE     5       5   27.5
6  2012  PHILADELPHIA     5       6   27.2
7  2012      ST LOUIS     4       5   28.2
8  2012       FLORIDA     3       4   27.9
9  2012        BOSTON     3       4   35.4

#### Q4 Cell 2. Use the cell below to enter your code for the 2nd cell of Q4.
Cell #2:

Display all observations that had more than 40 "Shots". Show all the columns for these observations.
Select and display all observations in Year 2011 that had more "Wins" than the average number of "Wins" for that particular year (2011).

In [37]:
df.loc[df['Shots'] > 40]

,Year,Team,Wins,Losses,Shots,ShotsAgainst,PenaltyInMinutes,SeasonWinner
11,2012,CHICAGO,2,4,40.2,26.5,14.8,N
41,2010,WASHINGTON,3,4,41.7,27.7,9.9,N
143,2003,DETROIT,0,4,42.8,30.0,9.0,N

In [40]:
df.loc[(df['Year'] == 2011) & (df['Wins'] > df['Wins'].mean()),:]

,Year,Team,Wins,Losses,Shots,ShotsAgainst,PenaltyInMinutes,SeasonWinner
16,2011,BOSTON,16,9,31.9,34.0,15.8,Y
17,2011,VANCOUVER,15,10,32.3,31.8,17.4,N
18,2011,TAMPA BAY,11,7,28.9,32.8,11.5,N
19,2011,SAN JOSE,9,9,36.9,31.6,15.3,N
20,2011,DETROIT,7,4,35.2,33.1,11.4,N
21,2011,NASHVILLE,6,6,29.5,29.5,10.1,N

#### Q4 Cell 3. Use the cell below to enter your code for the 3rd cell of Q4. 
Cell #3:

Notice that the "SeasonWinner" column indicates the season winner for a given year (The value of that column is "Y" if winner of the "Year"). Find out which team won the season the most across the years. Do the necessary operation in Pandas and print out a single output (can be a table or a string) that states the team's name and the number of season wins.

In [185]:
dfGroupedby = df.groupby(df['SeasonWinner'] == 'Y')
print(dfGroupedby['Team'].value_counts())
a = df.loc[(df['SeasonWinner'] == 'Y')] 
winCount = 0
x = a
for i in a:
    if i in x:
        winCount += 1
    if winCount > 1:
        print(i.value_counts)
print('best team is', df.loc(df['SeasonWinner'] == 'Y'))

SeasonWinner  Team
False         PHILADELPHIA    10
              SAN JOSE        10
              DETROIT          9
              NEW JERSEY       9
              OTTAWA           9
              VANCOUVER        9
              BOSTON           7
              MONTREAL         7
              NASHVILLE        7
              WASHINGTON       7
              COLORADO         6
              DALLAS           6
              NY RANGERS       6
              PITTSBURGH       6
              ST LOUIS         6
              ANAHEIM          5
              BUFFALO          5
              CALGARY          5
              CHICAGO          4
              LOS ANGELES      4
              NY ISLANDERS     4
              PHOENIX          4
              TAMPA BAY        4
              TORONTO          4
              CAROLINA         3
              EDMONTON         3
              MINNESOTA        3
              ATLANTA          1
              COLUMBUS         1
              FLORIDA          1
True          DETROIT          2
              ANAHEIM          1
              BOSTON           1
              CAROLINA         1
              CHICAGO          1
              COLORADO         1
              LOS ANGELES      1
              NEW JERSEY       1
              PITTSBURGH       1
              TAMPA BAY        1
Name: count, dtype: int64

AttributeError: 'str' object has no attribute 'value_counts'